# build environment
FROM node:12.2.0-alpine
WORKDIR '/app'

#TODO maybe remove?
# ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json ./
RUN npm install --silent

#TODO maybe remove?
# RUN npm install react-scripts@3.3.0 -g --silent
COPY . .
CMD [ "npm", "run", "start" ]