FROM node:12.2.0-alpine
# Create app directory
WORKDIR '/app'
# /usr/src/app
# Install app dependencies
COPY ./package.json ./
# COPY package*.json ./

RUN npm install
# Copy app source code
COPY . .

#Expose port and start application
CMD [ "npm", "run", "dev" ]